// Code generated by mockery v2.37.1. DO NOT EDIT.

package generic

import (
	aiven "github.com/aiven/aiven-go-client"
	mock "github.com/stretchr/testify/mock"
)

// MockKafkaAclInterface is an autogenerated mock type for the KafkaAclInterface type
type MockKafkaAclInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: project, service, req
func (_m *MockKafkaAclInterface) Create(project string, service string, req aiven.CreateKafkaACLRequest) (*aiven.KafkaACL, error) {
	ret := _m.Called(project, service, req)

	var r0 *aiven.KafkaACL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, aiven.CreateKafkaACLRequest) (*aiven.KafkaACL, error)); ok {
		return rf(project, service, req)
	}
	if rf, ok := ret.Get(0).(func(string, string, aiven.CreateKafkaACLRequest) *aiven.KafkaACL); ok {
		r0 = rf(project, service, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.KafkaACL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, aiven.CreateKafkaACLRequest) error); ok {
		r1 = rf(project, service, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: project, service, aclID
func (_m *MockKafkaAclInterface) Delete(project string, service string, aclID string) error {
	ret := _m.Called(project, service, aclID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(project, service, aclID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: project, serviceName
func (_m *MockKafkaAclInterface) List(project string, serviceName string) ([]*aiven.KafkaACL, error) {
	ret := _m.Called(project, serviceName)

	var r0 []*aiven.KafkaACL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*aiven.KafkaACL, error)); ok {
		return rf(project, serviceName)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*aiven.KafkaACL); ok {
		r0 = rf(project, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aiven.KafkaACL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockKafkaAclInterface creates a new instance of MockKafkaAclInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaAclInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaAclInterface {
	mock := &MockKafkaAclInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
