// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockCA is an autogenerated mock type for the CA type
type MockCA struct {
	mock.Mock
}

// Get provides a mock function with given fields: project
func (_m *MockCA) Get(project string) (string, error) {
	ret := _m.Called(project)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(project)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
