// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import (
	aiven "github.com/aiven/aiven-go-client"
	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: project, service
func (_m *MockInterface) Get(project string, service string) (*aiven.Service, error) {
	ret := _m.Called(project, service)

	var r0 *aiven.Service
	if rf, ok := ret.Get(0).(func(string, string) *aiven.Service); ok {
		r0 = rf(project, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
