# Default values for kafkarator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/nais/kafkarator/kafkarator
  pullPolicy: Always
  tag: latest

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

securityContext:
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1069
  runAsNonRoot: true
  runAsUser: 1069
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

aiven:
  projects: # Space separated list of Aiven projects with Kafka clusters available for this kafkarator instance
  token: "" # API token for Aiven with access to above mentioned projects
