# Default values for kafkarator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/kafkarator/kafkarator
  pullPolicy: IfNotPresent
  tag: latest # Overridden in main workflow

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 128Mi

caBundle: false

extraEnv: {}

featureFlags:
  generated_client: false

aiven:
  projects: # Space separated list of Aiven projects with Kafka clusters available for this kafkarator instance
  token: "" # API token for Aiven with access to above mentioned projects
