# Default values for kafkarator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/nais/kafkarator/kafkarator
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

caBundle: false

extraEnv: {}

aiven:
  projects: # Space separated list of Aiven projects with Kafka clusters available for this kafkarator instance
  token: "" # API token for Aiven with access to above mentioned projects
