FROM ghcr.io/astral-sh/uv:latest AS uv-provider

FROM europe-north1-docker.pkg.dev/nais-io/nais/images/deploy:latest

COPY --from=uv-provider /uv /usr/local/bin/
WORKDIR /canary/
COPY canary-deployer/pyproject.toml canary-deployer/uv.lock canary-deployer/deployer.py /canary/
RUN uv sync --frozen --no-dev
COPY canary-deployer/*.yaml /canary/
RUN /canary/.venv/bin/python -c "import deployer"
ENTRYPOINT ["/canary/.venv/bin/python", "/canary/deployer.py"]
