FROM golang:1.26 AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GO111MODULE=on

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -installsuffix cgo -o kafkarator cmd/kafkarator/*.go

FROM cgr.dev/chainguard/static:latest

WORKDIR /
COPY --from=builder /workspace/kafkarator /
CMD ["/kafkarator"]
