{{ if eq .Values.cluster.kind "management" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kafka-canary.fullname" . }}
  labels:
    {{- include "kafka-canary.labels" . | nindent 4 }}
spec:
  schedule: "*/30 * * * *"
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "kafka-canary.selectorLabels" . | nindent 8 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.deployer.image.repository }}:{{ .Values.deployer.image.tag }}"
              imagePullPolicy: {{ .Values.deployer.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ include "kafka-canary.fullname" . }}
              env:
                - name: CLUSTERS
                  value: "{{ .Values.clusters }}"
                - name: IMAGE
                  value: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag }}"
                - name: POOL
                  value: "{{ .Values.aiven_project }}"
{{ end }}
