{{ if eq .Values.cluster.kind "management" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-canary.serviceAccountName" . }}
  labels:
    {{- include "kafka-canary.labels" . | nindent 4 }}
{{ end }}
