{{ if eq .Values.cluster.kind "management" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-canary-deployer.fullname" . }}
  labels:
    {{- include "kafka-canary.labels" . | nindent 4 }}
stringData:
  APIKEY: "{{ .Values.api_key }}"
{{ end }}
