apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  egress: 
  - to:
    - namespaceSelector: 
        matchLabels:
          kubernetes.io/metadata.name: nais-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: hookd
          app.kubernetes.io/name: hookd
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
  - Egress
