apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kafka-canary.fullname" . }}
  labels:
    {{- include "kafka-canary.labels" . | nindent 4 }}
spec:
  egress:
    - to:  # TODO: Restrict to ingress/LB?
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: hookd
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector:
    matchLabels:
      {{ include "kafka-canary.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
