apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kafka-canary.fullname" . }}-post-install
  labels:
    {{- include "kafka-canary.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    {{- include "kafka-canary.job-template" . | nindent 4 }}
