{{ if eq .Values.cluster.kind "tenant" }}
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: {{ include "kafka-canary.fullname" . }}-{{ .Values.cluster.name }}
  labels:
    {{- include "kafka-canary.labels" . | nindent 4 }}
spec:
  pool: "{{ .Values.aiven_project }}"
  config:
    retentionHours: 24
  acl:
    - access: readwrite
      team: "nais-verification"
      application: kafkarator-canary
    - access: read
      team: "*"
      application: "*"
{{ end }}
