@startuml

title Kafkarator operation

control kubernetes as "Kubernetes"
control kafkarator as "Kafkarator"
boundary aiven as "Aiven"

loop until success
kubernetes -> kafkarator : Topic resource created/updated
kafkarator -> aiven : Create or update topics
kafkarator -> aiven : Create and/or delete ACLs
kafkarator -> kubernetes : Write back status and sync hash
note right: RolloutComplete
end

@enduml
