---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kafka-canary-alert.fullname" . }}
  labels:
    {{- include "kafka-canary-alert.labels" . | nindent 4 }}
spec:
  groups:
    - name: kafka-canary
      rules:
        - alert: AivenKafkaUnavailable
          expr: '(time()-min(kafkarator_canary_last_consumed) > 120) or absent(kafkarator_canary_last_consumed)'
          for: 5m
          labels:
            namespace: nais-verification
            severity: critical
          annotations:
            summary: Aiven Kafka is unavailable for applications in {{ pool }}
            consequence: Kafka is unavailable, probably for all applications
            action: |
              * Check that canary has valid Kafka credentials
              * Check that Aiven Kafka in {{ pool }} is up and running
              * Check canary logs: `kubectl logs -n nais-verification deploy/kafka-canary kafka-canary`

              Instrumentation: Coming soon!
