---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kafka-canary-alert.fullname" . }}
  labels:
    {{- include "kafka-canary-alert.labels" . | nindent 4 }}
spec:
  groups:
    - name: kafka-canary
      rules:
        - alert: AivenKafkaUnavailable
          expr: '(time()-min(kafkarator_canary_last_consumed) > 120) or absent(kafkarator_canary_last_consumed)'
          for: 5m
          labels:
            severity: critical
            feature: kafka-canary
            cluster: "{{ .Values.cluster }}"
            pool: "{{ .Values.pool }}"
            namespace: nais-system
          annotations:
            summary: Aiven Kafka in {{ .Values.pool }} is unavailable for applications in {{ .Values.cluster }}
            consequence: Kafka is unavailable, probably for all applications
            action: |
              * Check that canary has valid Kafka credentials
              * Check that Aiven Kafka in {{ .Values.pool }} is up and running
              * Check canary logs: `kubectl logs --namespace nais-verification deploy/kafka-canary kafka-canary`

              Instrumentation: Coming soon!
