---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kafka-canary-alert.fullname" . }}
  labels:
    {{- include "kafka-canary-alert.labels" . | nindent 4 }}
spec:
  groups:
    - name: kafka-canary
      rules:
        - alert: AivenKafkaUnavailable
          expr: '(time()-max(kafkarator_canary_last_consumed) > 120) or absent(kafkarator_canary_last_consumed)'
          for: 5m
          labels:
            severity: critical
            feature: kafka-canary
            cluster: "{{ .Values.cluster }}"
            pool: "{{ .Values.pool }}"
            tenant: "{{ .Values.tenant }}"
            namespace: nais-system
          annotations:
            summary: Aiven Kafka in {{ .Values.pool }} is unavailable for applications in {{ .Values.cluster }}
            consequence: Kafka is unavailable, probably for all applications
            action: |
              * Check that canary has valid Kafka credentials
              * Check that Aiven Kafka in {{ .Values.pool }} is up and running
              * Check canary logs: `kubectl logs --namespace nais-verification deploy/kafka-canary kafka-canary`

              Instrumentation: https://monitoring.nais.io/d/kafka-canary/kafka-canary?orgId=1&refresh=1m&var-ds=All&var-tenant={{ .Values.tenant }}
        - alert: AivenKafkaUnavailable
          expr: '(kafkarator_canary_transacted_messages_total = 0) or absent(kafkarator_canary_transacted_messags_total)'
          for: 5m
          labels:
            severity: critical
            feature: kafka-canary
            cluster: "{{ .Values.cluster }}"
            pool: "{{ .Values.pool }}"
            tenant: "{{ .Values.tenant }}"
            namespace: nais-system
          annotations:
            summary: Transactions in Aiven Kafka in {{ .Values.pool }} are unavailable for applications in {{ .Values.cluster }}
            consequence: Transactions in Kafka are unavailable, probably for all applications
            action: |
              * Check that canary has valid Kafka credentials
              * Check that Aiven Kafka in {{ .Values.pool }} is up and running
              * Check canary logs: `kubectl logs --namespace nais-verification deploy/kafka-canary kafka-canary`

              Instrumentation: https://monitoring.nais.io/d/kafka-canary/kafka-canary?orgId=1&refresh=1m&var-ds=All&var-tenant={{ .Values.tenant }}

        - alert: AivenKafkaCanaryNotDeployed
          expr: '(time() - max(kafkarator_canary_deploy_timestamp) > 3600)'
          for: 5m
          labels:
            severity: critical
            feature: kafka-canary
            cluster: "{{ .Values.cluster }}"
            pool: "{{ .Values.pool }}"
            tenant: "{{ .Values.tenant }}"
            namespace: nais-system
          annotations:
            summary: Aiven Kafka Canary in {{ .Values.tenant}}-{{ .Values.cluster }} has not been deployed in over an hour
            consequence: Kafka canary is unable to test that provisioning of credentials work
            action: |
              * Check canary deployer logs: `kubectl --context={{ .Values.tenant}}-management --namespace=nais-system logs -lapp.kubernetes.io/name=kafka-canary`
              * Check status of canary deployer jobs: `kubectl --context={{ .Values.tenant}}-management --namespace=nais-system describe job -lapp.kubernetes.io/name=kafka-canary`
              * Check status of canary deployer cronjob: `kubectl --context={{ .Values.tenant}}-management --namespace=nais-system describe cronjob kafka-canary-deployer`

              Instrumentation: https://monitoring.nais.io/d/kafka-canary/kafka-canary?orgId=1&refresh=1m&var-ds=All&var-tenant={{ .Values.tenant }}
