---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: mytopic
  namespace: basseng
  labels:
    team: basseng
spec:
  pool: dev-nais-dev
  config:
    cleanupPolicy: delete
    retentionHours: 900
    localRetentionHours: 100
  acl:
    - access: read
      team: basseng
      application: myapplication
    - access: write
      team: basseng
      application: otherapplication
