---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: mytopic
  namespace: default
  labels:
    team: default
spec:
  pool: nav-integration-test
  config:
    retentionHours: 900
  acl:
    - access: read
      team: default
      application: myapplication
    - access: write
      team: default
      application: otherapplication
    - access: read
      team: default
      additionalUser: sam.wright
