---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: othertopic
  labels:
    team: aura
spec:
  pool: nav-integration-test
  config:
    retentionHours: 900
  acl:
    - access: read
      team: myteam
      application: myapplication
    - access: write
      team: myteam
      application: otherapplication
