---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  namespace: default
  name: mytopic
  labels:
    team: aura
spec:
  pool: nav-integration-test
  config:
    retentionHours: 900
  acl:
    - access: read
      team: aura
