{{#if alert_enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka-canary-{{ cluster_name }}
  namespace: "{{ team }}"
  labels:
    team: "{{ team }}"
spec:
  groups:
    - name: kafka-canary
      rules:
        - alert: Aiven Kafka is unavailable
          expr: '(time()-min(kafkarator_canary_last_consumed) > 120) or absent(kafkarator_canary_last_consumed)'
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
          annotations:
            consequence: '{{ "Kafka is unavailable, probably for all applications in {{ $labels.tenant_cluster }}" }}'
            action: |
              * Check that canary has valid Kafka credentials
              * Check that Aiven Kafka in {{ pool }} is up and running
              * Check canary logs: `kubectl logs -n nais-verification deploy/kafka-canary kafka-canary`

              Instrumentation: <https://grafana.{{ tenant }}.cloud.nais.io/TODO>
{{/if}}
