---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: kafka-canary
  namespace: "{{ team }}"
  labels:
    team: "{{ team }}"
spec:
  replicas:
    min: 2
    max: 2
  image: "{{ image }}"
  kafka:
    pool: "{{ pool }}"
  prometheus:
    enabled: true
    path: /metrics
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  env:
    - name: CANARY_DEPLOY_START_TIME
      value: "{{ now }}"
    - name: CANARY_MESSAGE_INTERVAL
      value: 1s
    - name: CANARY_KAFKA_TOPIC
      value: "{{ canary_kafka_topic }}"
    - name: CANARY_KAFKA_TRANSACTION_TOPIC
      value: "{{ canary_kafka_transaction_topic }}"
    - name: CANARY_ENABLE_TRANSACTION
      value: "{{ canary_enable_transaction }}"
    - name: CANARY_KAFKA_GROUP_ID
      value: "{{ groupid }}"
    - name: CANARY_LOG_FORMAT
      value: json
    - name: CANARY_METRICS_ADDRESS
      value: 0.0.0.0:8080
