---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: kafka-canary-{{ cluster_name }}
  namespace: "{{ team }}"
  labels:
    team: "{{ team }}"
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: "{{ pool }}"
  config:
    partitions: 2
    retentionHours: 24
  acl:
    - access: readwrite
      team: "nais-verification"
      application: kafkarator-canary
    - access: readwrite
      team: "nais-verification"
      application: kafka-canary
    - access: read
      team: "*"
      application: "*"
