{
 "title": "Status in $ds",
 "panels": [
  {
   "title": "Healthy",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"kafka-canary\", namespace=\"nais-verification\"})"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{container=\"kafka-canary\", namespace=\"nais-verification\"})"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\",namespace=\"nais-verification\",pod=~\"^kafkarator-.+\"})"
    }
   ]
  },
  {
   "title": "# of restarts",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"kafka-canary\", namespace=\"nais-verification\"})"
    }
   ]
  },
  {
   "title": "App version",
   "type": "singlestat",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(kube_pod_container_info{container=\"kafka-canary\",namespace=\"nais-verification\"}, \"version\", \"$1\", \"image\", \".*:(.*)\")",
     "legendFormat": "{{ version }}"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Canary - $ds",
 "panels": [
  {
   "title": "Age",
   "type": "gauge",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - max(kafkarator_canary_start_timestamp)"
    }
   ]
  },
  {
   "title": "Last consumed",
   "type": "gauge",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - max(kafkarator_canary_last_consumed)"
    }
   ]
  },
  {
   "title": "Last produced",
   "type": "gauge",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - max(kafkarator_canary_last_produced)"
    }
   ]
  },
  {
   "title": "Message latency percentiles",
   "type": "graph",
   "description": "How long does it take from a message is produced until it is seen by the consumer?",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kafkarator_canary_consume_latency_bucket[5m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafkarator_canary_consume_latency_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(kafkarator_canary_consume_latency_bucket[5m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kafkarator_canary_consume_latency_bucket[5m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Offset skew",
   "type": "graph",
   "description": "How many messages have been produced, but not yet consumed?",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafkarator_canary_last_produced_offset)-sum(kafkarator_canary_last_consumed_offset)"
    }
   ]
  },
  {
   "title": "Sync producer latency percentiles",
   "type": "graph",
   "description": "How long does it take to produce a message and persist it on the Kafka pool?",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kafkarator_canary_produce_latency_bucket[5m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafkarator_canary_produce_latency_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(kafkarator_canary_produce_latency_bucket[5m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kafkarator_canary_produce_latency_bucket[5m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}
{
 "title": "Resource usage",
 "panels": [
  {
   "title": "Memory usage - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"nais-verification\",container=\"kafka-canary\",resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"nais-verification\",container=\"kafka-canary\",resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"nais-verification\",container=\"kafka-canary\"}) by (pod)",
     "legendFormat": "working set {{ pod }}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"nais-verification\",container=\"kafka-canary\"}) by (pod)",
     "legendFormat": "Resident set size {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU usage - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"nais-verification\",container=\"kafka-canary\",resource=\"cpu\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"nais-verification\",container=\"kafka-canary\",resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"kafka-canary\",namespace=\"nais-verification\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}