{
 "title": "Status in $ds",
 "panels": [
  {
   "title": "Healthy",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"kafkarator\", namespace=\"nais-system\"})"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{container=\"kafkarator\", namespace=\"nais-system\"})"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\",namespace=\"nais-system\",pod=~\"^kafkarator-.+\"})"
    }
   ]
  },
  {
   "title": "# of restarts",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"kafkarator\", namespace=\"nais-system\"})"
    }
   ]
  },
  {
   "title": "App version",
   "type": "singlestat",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(kube_pod_container_info{container=\"kafkarator\",namespace=\"nais-system\"}, \"version\", \"$1\", \"image\", \".*:(.*)\")",
     "legendFormat": "{{ version }}"
    }
   ]
  }
 ]
}
{
 "title": "Kafka details - $ds",
 "panels": [
  {
   "title": "Number of broker nodes",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafkarator_kafka_pool_nodes_count) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Kafka version",
   "type": "singlestat",
   "valueName": "name",
   "targets": [
    { "expr": "kafkarator_kafka_pool_info", "legendFormat": "{{ pool }}: {{ version }}" }
   ]
  },
  {
   "title": "Kafka plan",
   "type": "singlestat",
   "valueName": "name",
   "targets": [
    { "expr": "kafkarator_kafka_pool_info", "legendFormat": "{{ pool }}: {{ plan }}" }
   ]
  }
 ]
}
{
 "title": "Kafka usage - $ds",
 "panels": [
  {
   "title": "Topics - $ds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafkarator_topics) by (source, pool)",
     "legendFormat": "{{ pool }} - {{ source }}"
    }
   ]
  },
  {
   "title": "ACLs - $ds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kafkarator_acls) by (pool)", "legendFormat": "{{ pool }}" }
   ]
  }
 ]
}
{
 "title": "Resource usage",
 "panels": [
  {
   "title": "Memory usage - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"nais-system\",container=\"kafkarator\",resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"nais-system\",container=\"kafkarator\",resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"nais-system\",container=\"kafkarator\"}) by (pod)",
     "legendFormat": "working set {{ pod }}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"nais-system\",container=\"kafkarator\"}) by (pod)",
     "legendFormat": "Resident set size {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU usage - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"nais-system\",container=\"kafkarator\",resource=\"cpu\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"nais-system\",container=\"kafkarator\",resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"kafkarator\",namespace=\"nais-system\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Processing",
 "panels": [
  {
   "title": "Topics processed - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafkarator_topics_processed) by (synchronization_state)",
     "legendFormat": "{{ synchronization_state }}"
    }
   ]
  },
  {
   "title": "Streams processed - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafkarator_streams_processed) by (synchronization_state)",
     "legendFormat": "{{ synchronization_state }}"
    }
   ]
  }
 ]
}
{
 "title": "Aiven Latency - $aiven_op",
 "panels": [
  {
   "title": "$ds",
   "type": "heatmap",
   "repeat": "ds",
   "targets": [
    {
     "expr": "sum(increase(kafkarator_aiven_latency_bucket{operation=\"$aiven_op\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}