// Code generated by mockery v2.37.1. DO NOT EDIT.

package manager

import (
	aiven "github.com/aiven/aiven-go-client"
	mock "github.com/stretchr/testify/mock"
)

// MockSchemaRegistryAclInterface is an autogenerated mock type for the SchemaRegistryAclInterface type
type MockSchemaRegistryAclInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: project, service, req
func (_m *MockSchemaRegistryAclInterface) Create(project string, service string, req aiven.CreateKafkaSchemaRegistryACLRequest) (*aiven.KafkaSchemaRegistryACL, error) {
	ret := _m.Called(project, service, req)

	var r0 *aiven.KafkaSchemaRegistryACL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, aiven.CreateKafkaSchemaRegistryACLRequest) (*aiven.KafkaSchemaRegistryACL, error)); ok {
		return rf(project, service, req)
	}
	if rf, ok := ret.Get(0).(func(string, string, aiven.CreateKafkaSchemaRegistryACLRequest) *aiven.KafkaSchemaRegistryACL); ok {
		r0 = rf(project, service, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.KafkaSchemaRegistryACL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, aiven.CreateKafkaSchemaRegistryACLRequest) error); ok {
		r1 = rf(project, service, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: project, service, aclID
func (_m *MockSchemaRegistryAclInterface) Delete(project string, service string, aclID string) error {
	ret := _m.Called(project, service, aclID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(project, service, aclID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: project, serviceName
func (_m *MockSchemaRegistryAclInterface) List(project string, serviceName string) ([]*aiven.KafkaSchemaRegistryACL, error) {
	ret := _m.Called(project, serviceName)

	var r0 []*aiven.KafkaSchemaRegistryACL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*aiven.KafkaSchemaRegistryACL, error)); ok {
		return rf(project, serviceName)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*aiven.KafkaSchemaRegistryACL); ok {
		r0 = rf(project, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aiven.KafkaSchemaRegistryACL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSchemaRegistryAclInterface creates a new instance of MockSchemaRegistryAclInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchemaRegistryAclInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchemaRegistryAclInterface {
	mock := &MockSchemaRegistryAclInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
