// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	aiven "github.com/aiven/aiven-go-client"
	mock "github.com/stretchr/testify/mock"
)

// ServiceUser is an autogenerated mock type for the ServiceUser type
type ServiceUser struct {
	mock.Mock
}

// Create provides a mock function with given fields: project, service, req
func (_m *ServiceUser) Create(project string, service string, req aiven.CreateServiceUserRequest) (*aiven.ServiceUser, error) {
	ret := _m.Called(project, service, req)

	var r0 *aiven.ServiceUser
	if rf, ok := ret.Get(0).(func(string, string, aiven.CreateServiceUserRequest) *aiven.ServiceUser); ok {
		r0 = rf(project, service, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.ServiceUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, aiven.CreateServiceUserRequest) error); ok {
		r1 = rf(project, service, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: project, service, user
func (_m *ServiceUser) Delete(project string, service string, user string) error {
	ret := _m.Called(project, service, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(project, service, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: project, serviceName
func (_m *ServiceUser) List(project string, serviceName string) ([]*aiven.ServiceUser, error) {
	ret := _m.Called(project, serviceName)

	var r0 []*aiven.ServiceUser
	if rf, ok := ret.Get(0).(func(string, string) []*aiven.ServiceUser); ok {
		r0 = rf(project, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aiven.ServiceUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
