{{ if eq .Values.cluster.kind "management" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kafka-canary-deployer.fullname" . }}
  labels:
    {{- include "kafka-canary-deployer.labels" . | nindent 4 }}
spec:
  schedule: "*/30 * * * *"
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "kafka-canary-deployer.selectorLabels" . | nindent 8 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ include "kafka-canary-deployer.fullname" . }}
              image: "{{ .Values.deployer.image.repository }}:{{ .Values.deployer.image.tag }}"
              imagePullPolicy: {{ .Values.deployer.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ include "kafka-canary-deployer.fullname" . }}
              env:
                - name: IMAGE
                  value: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag }}"
                - name: TEAM
                  value: "nais-verification"
                - name: TOPIC_BASE
                  value: "kafka-canary"
                - name: CLUSTER_POOLS
                  value: "{{ .Values.cluster_pools }}"
{{ end }}
