{{ if eq .Values.cluster.kind "management" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kafka-canary-deployer.fullname" . }}
  labels:
    {{- include "kafka-canary-deployer.labels" . | nindent 4 }}
spec:
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: hookd
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector:
    matchLabels:
      {{ include "kafka-canary-deployer.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
{{ end }}
