// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package topic

import (
	"context"

	"github.com/aiven/aiven-go-client/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockInterface
func (_mock *MockInterface) Create(ctx context.Context, project string, service string, req aiven.CreateKafkaTopicRequest) error {
	ret := _mock.Called(ctx, project, service, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, aiven.CreateKafkaTopicRequest) error); ok {
		r0 = returnFunc(ctx, project, service, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - service string
//   - req aiven.CreateKafkaTopicRequest
func (_e *MockInterface_Expecter) Create(ctx interface{}, project interface{}, service interface{}, req interface{}) *MockInterface_Create_Call {
	return &MockInterface_Create_Call{Call: _e.mock.On("Create", ctx, project, service, req)}
}

func (_c *MockInterface_Create_Call) Run(run func(ctx context.Context, project string, service string, req aiven.CreateKafkaTopicRequest)) *MockInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 aiven.CreateKafkaTopicRequest
		if args[3] != nil {
			arg3 = args[3].(aiven.CreateKafkaTopicRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_Create_Call) Return(err error) *MockInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_Create_Call) RunAndReturn(run func(ctx context.Context, project string, service string, req aiven.CreateKafkaTopicRequest) error) *MockInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockInterface
func (_mock *MockInterface) Delete(ctx context.Context, project string, service string, topic string) error {
	ret := _mock.Called(ctx, project, service, topic)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, project, service, topic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - service string
//   - topic string
func (_e *MockInterface_Expecter) Delete(ctx interface{}, project interface{}, service interface{}, topic interface{}) *MockInterface_Delete_Call {
	return &MockInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, project, service, topic)}
}

func (_c *MockInterface_Delete_Call) Run(run func(ctx context.Context, project string, service string, topic string)) *MockInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_Delete_Call) Return(err error) *MockInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, project string, service string, topic string) error) *MockInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockInterface
func (_mock *MockInterface) Get(ctx context.Context, project string, service string, topic string) (*aiven.KafkaTopic, error) {
	ret := _mock.Called(ctx, project, service, topic)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *aiven.KafkaTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*aiven.KafkaTopic, error)); ok {
		return returnFunc(ctx, project, service, topic)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *aiven.KafkaTopic); ok {
		r0 = returnFunc(ctx, project, service, topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.KafkaTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, project, service, topic)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - service string
//   - topic string
func (_e *MockInterface_Expecter) Get(ctx interface{}, project interface{}, service interface{}, topic interface{}) *MockInterface_Get_Call {
	return &MockInterface_Get_Call{Call: _e.mock.On("Get", ctx, project, service, topic)}
}

func (_c *MockInterface_Get_Call) Run(run func(ctx context.Context, project string, service string, topic string)) *MockInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_Get_Call) Return(kafkaTopic *aiven.KafkaTopic, err error) *MockInterface_Get_Call {
	_c.Call.Return(kafkaTopic, err)
	return _c
}

func (_c *MockInterface_Get_Call) RunAndReturn(run func(ctx context.Context, project string, service string, topic string) (*aiven.KafkaTopic, error)) *MockInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockInterface
func (_mock *MockInterface) List(ctx context.Context, project string, service string) ([]*aiven.KafkaListTopic, error) {
	ret := _mock.Called(ctx, project, service)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*aiven.KafkaListTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*aiven.KafkaListTopic, error)); ok {
		return returnFunc(ctx, project, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*aiven.KafkaListTopic); ok {
		r0 = returnFunc(ctx, project, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aiven.KafkaListTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, project, service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - service string
func (_e *MockInterface_Expecter) List(ctx interface{}, project interface{}, service interface{}) *MockInterface_List_Call {
	return &MockInterface_List_Call{Call: _e.mock.On("List", ctx, project, service)}
}

func (_c *MockInterface_List_Call) Run(run func(ctx context.Context, project string, service string)) *MockInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_List_Call) Return(kafkaListTopics []*aiven.KafkaListTopic, err error) *MockInterface_List_Call {
	_c.Call.Return(kafkaListTopics, err)
	return _c
}

func (_c *MockInterface_List_Call) RunAndReturn(run func(ctx context.Context, project string, service string) ([]*aiven.KafkaListTopic, error)) *MockInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockInterface
func (_mock *MockInterface) Update(ctx context.Context, project string, service string, topic string, req aiven.UpdateKafkaTopicRequest) error {
	ret := _mock.Called(ctx, project, service, topic, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, aiven.UpdateKafkaTopicRequest) error); ok {
		r0 = returnFunc(ctx, project, service, topic, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - service string
//   - topic string
//   - req aiven.UpdateKafkaTopicRequest
func (_e *MockInterface_Expecter) Update(ctx interface{}, project interface{}, service interface{}, topic interface{}, req interface{}) *MockInterface_Update_Call {
	return &MockInterface_Update_Call{Call: _e.mock.On("Update", ctx, project, service, topic, req)}
}

func (_c *MockInterface_Update_Call) Run(run func(ctx context.Context, project string, service string, topic string, req aiven.UpdateKafkaTopicRequest)) *MockInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 aiven.UpdateKafkaTopicRequest
		if args[4] != nil {
			arg4 = args[4].(aiven.UpdateKafkaTopicRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_Update_Call) Return(err error) *MockInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_Update_Call) RunAndReturn(run func(ctx context.Context, project string, service string, topic string, req aiven.UpdateKafkaTopicRequest) error) *MockInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}
