// Code generated by mockery v2.53.2. DO NOT EDIT.

package topic

import (
	context "context"

	aiven "github.com/aiven/aiven-go-client/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, project, service, req
func (_m *MockInterface) Create(ctx context.Context, project string, service string, req aiven.CreateKafkaTopicRequest) error {
	ret := _m.Called(ctx, project, service, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, aiven.CreateKafkaTopicRequest) error); ok {
		r0 = rf(ctx, project, service, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, project, service, topic
func (_m *MockInterface) Delete(ctx context.Context, project string, service string, topic string) error {
	ret := _m.Called(ctx, project, service, topic)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, project, service, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, project, service, topic
func (_m *MockInterface) Get(ctx context.Context, project string, service string, topic string) (*aiven.KafkaTopic, error) {
	ret := _m.Called(ctx, project, service, topic)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *aiven.KafkaTopic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*aiven.KafkaTopic, error)); ok {
		return rf(ctx, project, service, topic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *aiven.KafkaTopic); ok {
		r0 = rf(ctx, project, service, topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.KafkaTopic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, project, service, topic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, project, service
func (_m *MockInterface) List(ctx context.Context, project string, service string) ([]*aiven.KafkaListTopic, error) {
	ret := _m.Called(ctx, project, service)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*aiven.KafkaListTopic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*aiven.KafkaListTopic, error)); ok {
		return rf(ctx, project, service)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*aiven.KafkaListTopic); ok {
		r0 = rf(ctx, project, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aiven.KafkaListTopic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, project, service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, project, service, topic, req
func (_m *MockInterface) Update(ctx context.Context, project string, service string, topic string, req aiven.UpdateKafkaTopicRequest) error {
	ret := _m.Called(ctx, project, service, topic, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, aiven.UpdateKafkaTopicRequest) error); ok {
		r0 = rf(ctx, project, service, topic, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
