// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package acl

import (
	"github.com/nais/liberator/pkg/apis/kafka.nais.io/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// ACLs provides a mock function for the type MockSource
func (_mock *MockSource) ACLs() kafka_nais_io_v1.TopicACLs {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ACLs")
	}

	var r0 kafka_nais_io_v1.TopicACLs
	if returnFunc, ok := ret.Get(0).(func() kafka_nais_io_v1.TopicACLs); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kafka_nais_io_v1.TopicACLs)
		}
	}
	return r0
}

// MockSource_ACLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ACLs'
type MockSource_ACLs_Call struct {
	*mock.Call
}

// ACLs is a helper method to define mock.On call
func (_e *MockSource_Expecter) ACLs() *MockSource_ACLs_Call {
	return &MockSource_ACLs_Call{Call: _e.mock.On("ACLs")}
}

func (_c *MockSource_ACLs_Call) Run(run func()) *MockSource_ACLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_ACLs_Call) Return(topicACLs kafka_nais_io_v1.TopicACLs) *MockSource_ACLs_Call {
	_c.Call.Return(topicACLs)
	return _c
}

func (_c *MockSource_ACLs_Call) RunAndReturn(run func() kafka_nais_io_v1.TopicACLs) *MockSource_ACLs_Call {
	_c.Call.Return(run)
	return _c
}

// Pool provides a mock function for the type MockSource
func (_mock *MockSource) Pool() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pool")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_Pool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pool'
type MockSource_Pool_Call struct {
	*mock.Call
}

// Pool is a helper method to define mock.On call
func (_e *MockSource_Expecter) Pool() *MockSource_Pool_Call {
	return &MockSource_Pool_Call{Call: _e.mock.On("Pool")}
}

func (_c *MockSource_Pool_Call) Run(run func()) *MockSource_Pool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Pool_Call) Return(s string) *MockSource_Pool_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_Pool_Call) RunAndReturn(run func() string) *MockSource_Pool_Call {
	_c.Call.Return(run)
	return _c
}

// TopicName provides a mock function for the type MockSource
func (_mock *MockSource) TopicName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopicName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_TopicName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopicName'
type MockSource_TopicName_Call struct {
	*mock.Call
}

// TopicName is a helper method to define mock.On call
func (_e *MockSource_Expecter) TopicName() *MockSource_TopicName_Call {
	return &MockSource_TopicName_Call{Call: _e.mock.On("TopicName")}
}

func (_c *MockSource_TopicName_Call) Run(run func()) *MockSource_TopicName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_TopicName_Call) Return(s string) *MockSource_TopicName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_TopicName_Call) RunAndReturn(run func() string) *MockSource_TopicName_Call {
	_c.Call.Return(run)
	return _c
}
