// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package acl

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockInterface
func (_mock *MockInterface) Create(ctx context.Context, project string, service string, isStream bool, req CreateKafkaACLRequest) error {
	ret := _mock.Called(ctx, project, service, isStream, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool, CreateKafkaACLRequest) error); ok {
		r0 = returnFunc(ctx, project, service, isStream, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - service string
//   - isStream bool
//   - req CreateKafkaACLRequest
func (_e *MockInterface_Expecter) Create(ctx interface{}, project interface{}, service interface{}, isStream interface{}, req interface{}) *MockInterface_Create_Call {
	return &MockInterface_Create_Call{Call: _e.mock.On("Create", ctx, project, service, isStream, req)}
}

func (_c *MockInterface_Create_Call) Run(run func(ctx context.Context, project string, service string, isStream bool, req CreateKafkaACLRequest)) *MockInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 CreateKafkaACLRequest
		if args[4] != nil {
			arg4 = args[4].(CreateKafkaACLRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_Create_Call) Return(err error) *MockInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_Create_Call) RunAndReturn(run func(ctx context.Context, project string, service string, isStream bool, req CreateKafkaACLRequest) error) *MockInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockInterface
func (_mock *MockInterface) Delete(ctx context.Context, project string, service string, acl Acl) error {
	ret := _mock.Called(ctx, project, service, acl)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, Acl) error); ok {
		r0 = returnFunc(ctx, project, service, acl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - service string
//   - acl Acl
func (_e *MockInterface_Expecter) Delete(ctx interface{}, project interface{}, service interface{}, acl interface{}) *MockInterface_Delete_Call {
	return &MockInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, project, service, acl)}
}

func (_c *MockInterface_Delete_Call) Run(run func(ctx context.Context, project string, service string, acl Acl)) *MockInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 Acl
		if args[3] != nil {
			arg3 = args[3].(Acl)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_Delete_Call) Return(err error) *MockInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, project string, service string, acl Acl) error) *MockInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockInterface
func (_mock *MockInterface) List(ctx context.Context, project string, serviceName string) ([]*Acl, error) {
	ret := _mock.Called(ctx, project, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*Acl
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*Acl, error)); ok {
		return returnFunc(ctx, project, serviceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*Acl); ok {
		r0 = returnFunc(ctx, project, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Acl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, project, serviceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - serviceName string
func (_e *MockInterface_Expecter) List(ctx interface{}, project interface{}, serviceName interface{}) *MockInterface_List_Call {
	return &MockInterface_List_Call{Call: _e.mock.On("List", ctx, project, serviceName)}
}

func (_c *MockInterface_List_Call) Run(run func(ctx context.Context, project string, serviceName string)) *MockInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_List_Call) Return(acls []*Acl, err error) *MockInterface_List_Call {
	_c.Call.Return(acls, err)
	return _c
}

func (_c *MockInterface_List_Call) RunAndReturn(run func(ctx context.Context, project string, serviceName string) ([]*Acl, error)) *MockInterface_List_Call {
	_c.Call.Return(run)
	return _c
}
