# Default values for kafka-canary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster:
  name: "" # Mapped in fasit
  kind: "" # Mapped in fasit
aiven_project: "" # Mapped in fasit
tenant: "" # Mapped in fasit
