# Default values for kafka-canary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# cluster_pools contains a list of cluster=pool mappings
cluster_pools: "" # Mapped in fasit
# tenant is the name of the tenant this installation is for
tenant: "" # Mapped in fasit
# alert_enabled indicates if the alert should be installed when installing the canary
alert_enabled: false
# deploy_server is the endpoint that hookd listens on (including port if needed)
deploy_server: "" # Mapped in fasit
# deploy_key_secret_name is the name of a secret that contains a DEPLOY_API_KEY (created by nais-verification feature)
deploy_key_secret_name: "nais-verification-deploy-key"

canary:
  image:
    repository: ghcr.io/nais/kafkarator/canary
    tag: latest # Overridden in fasit

deployer:
  image:
    repository: ghcr.io/nais/kafkarator/canary-deployer
    pullPolicy: IfNotPresent
    tag: latest # Overridden in fasit
