{{- if .Capabilities.APIVersions.Has "kyverno.io/v1" }}
{{- $valid := splitList " " .Values.aiven.projects }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-kafkarator
  annotations:
    policies.kyverno.io/title: 011 - Validate fields for Kafka resources.
    policies.kyverno.io/category: Nais
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Topic, Stream
    policies.kyverno.io/description: >-
      This policy validates that the fields for the given resources has allowed values.
      Currently only validates the pool field.
  labels:
    {{- include "kafkarator.labels" . | nindent 4 }}
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 15
  rules:
    - name: "validate-pool"
      match:
        all:
          - resources:
              kinds:
                - kafka.nais.io/v1/Topic
                - kafka.nais.io/v1/Stream
              operations:
                - "CREATE"
                - "UPDATE"
      validate:
        message: >-
          Kafka pool {{ "{{ request.object.spec.pool }}" | quote }} is not supported in this cluster.
          Allowed values: [{{ $valid | join ", " }}]

          Please see the documentation at https://docs.nais.io/persistence/kafka/how-to/create/
        deny:
          conditions:
            all:
              - key: {{ "{{ request.object.spec.pool }}" | quote }}
                operator: AnyNotIn
                value:
                  {{- range $valid }}
                  - {{ . | quote }}
                  {{- end }}
    - name: "validate-tiered-storage-not-compacted"
      match:
        all:
          - resources:
              kinds:
                - kafka.nais.io/v1/Topic
              operations:
                - "CREATE"
                - "UPDATE"
      validate:
        message: >-
          Compacted topics can not use tiered storage with local retention.
          Please remove the local retention configuration from the topic.

          Please see the documentation at https://docs.nais.io/persistence/kafka/how-to/create/
        cel:
          expressions:
            - expression: >-
                !has(object.spec.config) ||
                !has(object.spec.config.cleanupPolicy) ||
                object.spec.config.cleanupPolicy == 'delete' ||
                (
                (!has(object.spec.config.localRetentionBytes) || object.spec.config.localRetentionBytes < 0) &&
                (!has(object.spec.config.localRetentionHours) || object.spec.config.localRetentionHours < 0)
                )
{{- end }}
