apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafkarator.fullname" . }}
  labels:
    {{- include "kafkarator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kafkarator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafkarator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "kafkarator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1069
            runAsNonRoot: true
            runAsUser: 1069
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: KAFKARATOR_LOG_FORMAT
            value: json
          - name: KAFKARATOR_METRICS_ADDRESS
            value: 0.0.0.0:8080
          - name: KAFKARATOR_SCHEMA_REGISTRY_ACL_ENABLED
            value: {{ .Values.schemaRegistryACLEnabled | quote }}
          - name: KAFKARATOR_PROJECTS
            value: "{{ .Values.aiven.projects }}"
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "kafkarator.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.caBundle }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              name: ca-bundle-pem
              readOnly: true
              subPath: ca-bundle.pem
      volumes:
        - configMap:
            defaultMode: 420
            name: ca-bundle-pem
          name: ca-bundle-pem
{{- end}}
