apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kafkarator.fullname" . }}
  labels:
    {{- include "kafkarator.labels" . | nindent 4 }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: "0.0.0.0/0"
  - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
  podSelector:
    matchLabels:
      {{- include "kafkarator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
