apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafkarator.fullname" . }}
  labels:
    {{- include "kafkarator.labels" . | nindent 4 }}
stringData:
  KAFKARATOR_AIVEN_TOKEN: {{ .Values.aiven.token | quote }}
