---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafkarator.serviceAccountName" . }}
  labels:
    {{- include "kafkarator.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kafkarator.fullname" . }}
  labels:
    {{- include "kafkarator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kafka.nais.io
  resources:
  - topics
  - streams
  verbs:
  - get
  - list
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kafkarator.fullname" . }}
  labels:
    {{- include "kafkarator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kafkarator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kafkarator.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
